/* eslint-disable @next/next/no-sync-scripts */
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="//app.usercentrics.eu" />
        <link rel="preconnect" href="//api.usercentrics.eu" />
        <link rel="preconnect" href="//privacy-proxy.usercentrics.eu" />
        <link
          rel="preload"
          href="//app.usercentrics.eu/browser-ui/latest/loader.js"
          as="script"
        />
        <link
          rel="preload"
          href="//privacy-proxy.usercentrics.eu/latest/uc-block.bundle.js"
          as="script"
        />
        <script
          id="usercentrics-cmp"
          src="https://app.usercentrics.eu/browser-ui/latest/loader.js"
          data-version="preview"
          data-settings-id={process.env.REACT_SETTINGS_ID}
          async
        ></script>
        <script
          type="application/javascript"
          src="https://privacy-proxy.usercentrics.eu/latest/uc-block.bundle.js"
        ></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
